//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Pose @__actions_default_in_Pose;
        
        public static SteamVR_Action_Skeleton @__actions_default_in_SkeletonLeftHand;
        
        public static SteamVR_Action_Skeleton @__actions_default_in_SkeletonRightHand;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TouchpadTouchLeft;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TouchpadTouchRight;
        
        public static SteamVR_Action_Single @__actions_default_in_SqueezeLeft;
        
        public static SteamVR_Action_Single @__actions_default_in_SqueezeRight;
        
        public static SteamVR_Action_Boolean @__actions_default_in_GripLeft;
        
        public static SteamVR_Action_Boolean @__actions_default_in_GripRight;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TouchpadClickLeft;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TouchpadClickRight;
        
        public static SteamVR_Action_Vector2 @__actions_default_in_TouchpadPositionLeft;
        
        public static SteamVR_Action_Vector2 @__actions_default_in_TouchpadPositionRight;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TriggerLeft;
        
        public static SteamVR_Action_Boolean @__actions_default_in_TriggerRight;
        
        public static SteamVR_Action_Boolean @__actions_default_in_MenuLeft;
        
        public static SteamVR_Action_Boolean @__actions_default_in_MenuRight;
        
        public static SteamVR_Action_Vibration @__actions_default_out_HapticLeft;
        
        public static SteamVR_Action_Vibration @__actions_default_out_HapticRight;
        
        public static SteamVR_Action_Vector2 @__actions_platformer_in_Move;
        
        public static SteamVR_Action_Boolean @__actions_platformer_in_Jump;
        
        public static SteamVR_Action_Vector2 @__actions_buggy_in_Steering;
        
        public static SteamVR_Action_Single @__actions_buggy_in_Throttle;
        
        public static SteamVR_Action_Boolean @__actions_buggy_in_Brake;
        
        public static SteamVR_Action_Boolean @__actions_buggy_in_Reset;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.@__actions_default_in_Pose.Initialize();
            SteamVR_Input.@__actions_default_in_SkeletonLeftHand.Initialize();
            SteamVR_Input.@__actions_default_in_SkeletonRightHand.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadTouchLeft.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadTouchRight.Initialize();
            SteamVR_Input.@__actions_default_in_SqueezeLeft.Initialize();
            SteamVR_Input.@__actions_default_in_SqueezeRight.Initialize();
            SteamVR_Input.@__actions_default_in_GripLeft.Initialize();
            SteamVR_Input.@__actions_default_in_GripRight.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadClickLeft.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadClickRight.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadPositionLeft.Initialize();
            SteamVR_Input.@__actions_default_in_TouchpadPositionRight.Initialize();
            SteamVR_Input.@__actions_default_in_TriggerLeft.Initialize();
            SteamVR_Input.@__actions_default_in_TriggerRight.Initialize();
            SteamVR_Input.@__actions_default_in_MenuLeft.Initialize();
            SteamVR_Input.@__actions_default_in_MenuRight.Initialize();
            SteamVR_Input.@__actions_default_out_HapticLeft.Initialize();
            SteamVR_Input.@__actions_default_out_HapticRight.Initialize();
            SteamVR_Input.@__actions_platformer_in_Move.Initialize();
            SteamVR_Input.@__actions_platformer_in_Jump.Initialize();
            SteamVR_Input.@__actions_buggy_in_Steering.Initialize();
            SteamVR_Input.@__actions_buggy_in_Throttle.Initialize();
            SteamVR_Input.@__actions_buggy_in_Brake.Initialize();
            SteamVR_Input.@__actions_buggy_in_Reset.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.@__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonLeftHand")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonRightHand")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadTouchLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadTouchRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeLeft = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_default_in_SqueezeLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeRight = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_default_in_SqueezeRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_GripLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GripLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_GripRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GripRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadClickLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadClickRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionLeft = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadPositionLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionRight = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_TouchpadPositionRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TriggerLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TriggerLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_TriggerRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_TriggerRight")));
            Valve.VR.SteamVR_Input.@__actions_default_in_MenuLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_MenuLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_in_MenuRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_MenuRight")));
            Valve.VR.SteamVR_Input.@__actions_default_out_HapticLeft = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_HapticLeft")));
            Valve.VR.SteamVR_Input.@__actions_default_out_HapticRight = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_HapticRight")));
            Valve.VR.SteamVR_Input.@__actions_platformer_in_Move = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_platformer_in_Move")));
            Valve.VR.SteamVR_Input.@__actions_platformer_in_Jump = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_platformer_in_Jump")));
            Valve.VR.SteamVR_Input.@__actions_buggy_in_Steering = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_buggy_in_Steering")));
            Valve.VR.SteamVR_Input.@__actions_buggy_in_Throttle = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_buggy_in_Throttle")));
            Valve.VR.SteamVR_Input.@__actions_buggy_in_Brake = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Brake")));
            Valve.VR.SteamVR_Input.@__actions_buggy_in_Reset = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Reset")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuRight,
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticRight,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuRight,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticRight};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_out_HapticRight};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuRight,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionRight,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[] {
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadTouchRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_GripRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadClickRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TouchpadPositionRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_TriggerRight,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuLeft,
                    Valve.VR.SteamVR_Input.@__actions_default_in_MenuRight,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.@__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.@__actions_buggy_in_Reset};
        }
    }
}
