//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonLeftHand;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonRightHand;
        
        public Valve.VR.SteamVR_Action_Boolean TouchpadTouchLeft;
        
        public Valve.VR.SteamVR_Action_Boolean TouchpadTouchRight;
        
        public Valve.VR.SteamVR_Action_Single SqueezeLeft;
        
        public Valve.VR.SteamVR_Action_Single SqueezeRight;
        
        public Valve.VR.SteamVR_Action_Boolean GripLeft;
        
        public Valve.VR.SteamVR_Action_Boolean GripRight;
        
        public Valve.VR.SteamVR_Action_Boolean TouchpadClickLeft;
        
        public Valve.VR.SteamVR_Action_Boolean TouchpadClickRight;
        
        public Valve.VR.SteamVR_Action_Vector2 TouchpadPositionLeft;
        
        public Valve.VR.SteamVR_Action_Vector2 TouchpadPositionRight;
        
        public Valve.VR.SteamVR_Action_Boolean TriggerLeft;
        
        public Valve.VR.SteamVR_Action_Boolean TriggerRight;
        
        public Valve.VR.SteamVR_Action_Boolean MenuLeft;
        
        public Valve.VR.SteamVR_Action_Boolean MenuRight;
    }
}
